newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your issue in this project.
  Please make sure that you follow our [Code of Conduct](https://github.com/gautamkrishnar/socli/blob/master/CODE_OF_CONDUCT.md)ğŸ™Œ while interacting with the project. Have a good day!
  
  
  
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨ You are awesome...
  Please adhere to our [Code of Conduct](https://github.com/gautamkrishnar/socli/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€
