# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project.Stack Overflow command line written in python. Using SoCLI you can search and browse Stack Overflow without leaving the terminal.  
  Please adhere to our [Code of Conduct](https://github.com/gautamkrishnar/socli/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ
  
  
  
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨ Stack Overflow command line written in python. Using SoCLI you can search and browse Stack Overflow without leaving the terminal.
  Please adhere to our [Code of Conduct](https://github.com/gautamkrishnar/socli/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€
